Docs update 2.5.0 stabilization
microsoft/MixedRealityToolkit-Unity pull request #8512
Opened 2020-09-09 20:03 UTC by hferrone

## Overview

## Changes
- Fixes: # .

## Verification
> This optional section is a place where you can detail the specific type of verification 
> you want from reviewers. For example, if you want reviewers to checkout the PR locally
> and validate the functionality of specific scenarios, provide instructions
> on the specific scenarios and what you want verified.
>
> If there are specific areas of concern or question feel free to highlight them here so
> that reviewers can watch out for those issues.
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

2020-09-10 17:53 UTC, davidkline-ms approved these changes
overall, looks good. approved pending the resolution of the offline discussion of the Getting Started page

2020-09-10 18:28 UTC, keveleigh commented on Documentation/Installation.md
> +# Installation Guide
One thing we've been using is ["Sentence case" for headers](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/DocumentationGuide.html#capitalization).

2020-09-10 18:28 UTC, keveleigh commented on Documentation/Installation.md
> +# Installation Guide
```suggestion
# Installation guide
```

2020-09-10 18:28 UTC, keveleigh commented on Documentation/WelcomeToMRTK.md
> +## Documentation Versioning
```suggestion
## Documentation versioning
```

2020-09-12 00:10 UTC, keveleigh commented
/azp run mrtk_docs

2020-09-12 00:12 UTC, keveleigh commented on Documentation/WelcomeToMRTK.md
> +> The Unity development journey currently uses **MRTK version 2.4.0** and **Unity 2019.3.15**. If you're working with other configurations it's still recommended that you start there, but you can als
We should probably recommend 2019.4 over 2019.3.

```suggestion
> The Unity development journey currently uses **MRTK version 2.4.0** and **Unity 2019.4**. If you're working with other configurations it's still recommended that you start there, but you can also refer to the [installation instructions](Installation.md).
```

2020-09-12 00:13 UTC, keveleigh commented on Documentation/WelcomeToMRTK.md
> +> The Unity development journey currently uses **MRTK version 2.4.0** and **Unity 2019.3.15**. If you're working with other configurations it's still recommended that you start there, but you can als
We should probably recommend Unity 2019.4 over 2019.3.

```suggestion
> The Unity development journey currently uses **MRTK version 2.4.0** and **Unity 2019.4**. If you're working with other configurations it's still recommended that you start there, but you can also refer to the [installation instructions](Installation.md).
```

2020-09-12 00:14 UTC, keveleigh commented on Documentation/WelcomeToMRTK.md
> +> The Unity development journey currently uses **MRTK version 2.4.0** and **Unity 2019.3.15**. If you're working with other configurations it's still recommended that you start there, but you can als
Do we also want to reference 2.5?

```suggestion
> The Unity development journey currently uses **MRTK version 2.5.0** and **Unity 2019.4**. If you're working with other configurations it's still recommended that you start there, but you can also refer to the [installation instructions](Installation.md).
```

2020-09-14 17:20 UTC, keveleigh commented
Looks like there are a couple broken links:

```
Build succeeded with warning.
[20-09-12 12:14:46.581]Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.TocDocumentProcessor.Save](../../toc.yml#L0)Invalid file link:(~/../../Documentation/GettingStartedWithTheMRTK.md).
[20-09-12 12:14:46.581]Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.TocDocumentProcessor.Save](../../toc.yml#L0)Invalid file link:(~/../../Documentation/GettingStartedWithTheMRTK.md).
[20-09-12 12:14:46.581]Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save](../../Documentation/Tools/HolographicRemoting.md#L82)Invalid file link:(~/../../Documentation/GettingStartedWithTheMRTK.md#getting-help).
[20-09-12 12:14:46.581]Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save](../../Documentation/Tools/HolographicRemoting.md#L109)Invalid file link:(~/../../Documentation/GettingStartedWithTheMRTK.md#getting-help).
[20-09-12 12:14:46.581]Warning:[BuildCommand.BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save](../../Documentation/GettingStartedWithMRTKAndXRSDK.md#L7)Invalid file link:(~/../../Documentation/GettingStartedWithTheMRTK.md).
```

2020-09-21 18:10 UTC, davidkline-ms commented
@hferrone, can you resolve the merge conflict?

2020-09-21 20:03 UTC, hferrone commented
@davidkline-ms That should do it 👍

2020-09-21 20:27 UTC, keveleigh commented
Looks like there's a .DS_Store file being committed. Is that needed?

2020-09-21 20:29 UTC, keveleigh commented
/azp run mrtk_docs

2020-09-21 20:50 UTC, keveleigh requested changes
Is the .DS_Store file necessary? We haven't had one in the past

2020-09-21 20:57 UTC, keveleigh approved these changes

2020-09-21 21:02 UTC, davidkline-ms commented
/azp run mrtk_docs

2020-09-21 21:18 UTC, merged