Cherry pick #9341 to mrtk_dev
microsoft/MixedRealityToolkit-Unity pull request #9435
Opened 2021-03-04 17:52 UTC by keveleigh

## Overview

Brings over the contents of #9341 from @polar-kev

2021-03-04 17:52 UTC, keveleigh commented
/azp run

2021-03-04 18:32 UTC, polar-kev requested changes

2021-03-04 18:32 UTC, polar-kev commented on Documentation/GettingStartedWithMRTKAndXRSDK.md
> +>See this page on the ***[new docs website](https:docs.microsoft.com/windows/mixed-reality/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk)***.
```suggestion
>See this page on the ***[new docs website](https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/configuration/getting-started-with-mrtk-and-xrsdk)***.
```

2021-03-04 18:39 UTC, keveleigh commented
/azp run

2021-03-04 23:45 UTC, polar-kev requested changes

2021-03-04 23:45 UTC, polar-kev commented on Documentation/GettingStartedWithTheMRTK.md
> +>We have a ***[new docs website](https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/welcome-to-mrtk)*** for Mixed Reality Toolkit Documentation.
```suggestion
>We have a ***[new docs website](https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/)*** for Mixed Reality Toolkit Documentation.
```

2021-03-04 23:45 UTC, polar-kev commented on Documentation/WelcomeToMRTK.md
> +>We have a ***[new docs website](https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/welcome-to-mrtk)*** for Mixed Reality Toolkit Documentation.
```suggestion
>We have a ***[new docs website](https://docs.microsoft.com/windows/mixed-reality/mrtk-unity)*** for Mixed Reality Toolkit Documentation.
```

2021-03-04 23:45 UTC, polar-kev commented on README.md
> +>We have a ***[new docs website](https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/welcome-to-mrtk)*** for Mixed Reality Toolkit Documentation.
```suggestion
>We have a ***[new docs website](https://docs.microsoft.com/windows/mixed-reality/mrtk-unity)*** for Mixed Reality Toolkit Documentation.
```

2021-03-04 23:50 UTC, keveleigh commented
/azp run mrtk_docs

2021-03-10 17:24 UTC, keveleigh commented
/azp run

2021-04-01 02:38 UTC, davidkline-ms approved these changes

2021-04-01 23:09 UTC, keveleigh commented
@polar-kev is this still needed and/or good to go?

2021-04-30 19:29 UTC, RogPodge commented
Closing this PR since some other PR's have sufficiently covered what we were trying to do here: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9436

2021-04-30 19:29 UTC, closed without merging